services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest #keeps up dated with latest version
    container_name: mealie
    restart: always
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - ./data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: ${TZ} #America/Anchorage
      BASE_URL: ${BASE_URL} #https://mealie.yourdomain.com
